// <auto-generated />
namespace Optica_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2tablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2tablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201708161824451_2tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
