//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optica_ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUserData()
        {
            this.AspNetHistorial = new HashSet<AspNetHistorial>();
        }
    
        public string UserDataId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TipoDocumento { get; set; }
        public string Entidad_EntityId { get; set; }
    
        public virtual AspNetEntitys AspNetEntitys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetHistorial> AspNetHistorial { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
