//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optica_ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRegistro
    {
        public string RegistroId { get; set; }
        public string Descripcion { get; set; }
        public string Resultado { get; set; }
        public string Tratamiento { get; set; }
    
        public virtual AspNetHistorial AspNetHistorial { get; set; }
    }
}
