//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optica_ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetHistorial
    {
        public System.DateTime Fecha { get; set; }
        public string HistorialId { get; set; }
        public string Medico_Id { get; set; }
        public string Paciente_Id { get; set; }
        public string UserData_UserDataId { get; set; }
    
        public virtual AspNetUserData AspNetUserData { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetRegistro AspNetRegistro { get; set; }
    }
}
